config/routes.rb
ChinaBeiBao::Application.routes.draw do
  devise_for :admins,
    :controllers => { :sessions => 'admins/sessions', :registrations => "admins/registrations" }
    
  root :to => "home#index"
  
  namespace :admin do
    root :to => 'home#index'
    resources :companies do
      resources :topics
      resources :articles
      resources :routes
    end
    resources :areas, :topics, :articles, :routes, :admins
  end
  
  
  resources :topics, :routes, :articles, :companies, :only => [:index, :show]
  match '/:slug' => 'areas#show', :as => :area
  match '/:slug/topics' => 'topics#index', :as => :area_topics
  match '/:slug/articles' => 'articles#index', :as => :area_articles
  match '/:slug/routes' => 'routes#index', :as => :area_routes  

end

app/models/article.rb
# coding : utf-8
class Article < ActiveRecord::Base
  belongs_to :area
  belongs_to :company
  
  validates_presence_of :title, :summary, :body, :area_id, :company_id
  validates_numericality_of :pv, :greater_than_or_equal_to => 0, :only_integer => true
  validates_attachment_size :cover, :less_than => 2.megabytes, :message => "必须小于2M"
  validates_attachment_content_type :cover, :content_type => ['image/jpeg', 'image/png', 'image/pjpeg', 'image/gif'],
    :message => "只能是图片"
  validates_attachment_presence :cover, :message => "不能为空字符"
  
  has_attached_file :cover,  
    :styles => {
      :thumb => "80x80#",
      :small => "400>",
      :normal => "690>" },
    :default_style => :normal,
    :url => "#{APP_CONFIG["upload_url"]}/:class/:attachment/:date_path/:id/:style_:hash_name.:extension",
    :path => "#{APP_CONFIG["upload_path"]}/:class/:attachment/:date_path/:id/:style_:hash_name.:extension",
    :default_url => "default/files/:style.jpg",
    :whiny => false
  
  # abnormal 不正常
  # normal 正常
  STATE = { :abnormal => 0, :normal => 1 }
  
  scope :top2, :order => "id desc", :limit => 2
end

app/controllers/admin/articles_controller.rb
# coding : utf-8
class Admin::ArticlesController < Admin::ApplicationController
  before_filter :init_company
  
  def index
    conditions = { :company_id => @company.id } if !@company.blank?
    @articles = initialize_grid(Article, :include => [:area, :company], :conditions => conditions || nil)
  end
  
  def new
    @article = Article.new
  end
  
  def create
    @article = Article.new(params[:article])
    if @article.save
      flash[:notice] = "专题创建成功，你可以继续操作！"
      redirect_path
    else
      render :new
    end
  end
  
  def edit
    @article = Article.find(params[:id])
  end
  
  def update
    @article = Article.find(params[:id])
    if @article.update_attributes(params[:article])
      flash[:notice] = "专题更新成功，你可以继续操作！"
      redirect_path
    else
      render :edit
    end
  end
  
  def destroy
    @article = Article.find(params[:id])
    if @article.destroy
      flash[:notice] = "专题删除成功！"
    else
      flash[:alert] = "专题删除失败！"
    end
    redirect_path
  end
  
  private
  def init_company
    @company = Company.find(params[:company_id]) if !params[:company_id].blank?
  end
  
  def redirect_path
    if !@company.blank?
      redirect_to admin_company_articles_path(@company)
    else
      redirect_to admin_articles_path
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  
  before_filter :load_areas, :load_sidebar
  
  def index
    if !params[:slug].blank?
      @area = Area.where(:slug => params[:slug]).first
      @articles = @area.articles.order("id desc").page(params[:page]).per(15)
    else
      @articles = Article.order("id desc").page(params[:page]).per(15)
    end
  end
  
  def show
    @article = Article.find(params[:id])
    @articles = Article.all.sample(5)
  end
  
end

app/helpers/admin/articles_helper.rb
module Admin::ArticlesHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/admin/articles/_base.html.erb
<%= content_for :page_header do -%>
  <% if ["index"].index(action_name) -%>
    <h1><%= @company.blank? ? "文章列表" : "#{@company.name}的文章列表" %></h1>
  <% end -%>
  <% if ["new", "create"].index(action_name) -%>
    <h1><%= @company.blank? ? "创建文章" : "创建#{@company.name}的文章" %></h1>
  <% end -%>
  <% if ["edit", "update"].index(action_name) -%>
    <h1><%= @company.blank? ? "修改文章" : "修改#{@company.name}的文章" %></h1>
  <% end -%>
<% end -%>
<%= content_for :sidebar do -%>
  <% if ["index"].index(action_name) -%> 
    <div class="button_to_add_new">
      <div class="button_layout">
        <% if @company.blank? %>
          <a href="<%= new_admin_article_path %>"><span>添加新的文章</span></a>
        <% else -%>
          <a href="<%= new_admin_company_article_path(@company) %>"><span>添加新的文章</span></a>
        <% end -%>
      </div>
    </div>      
  <% end -%>
  <% if ["new", "create", "edit", "update"].index(action_name) -%>
    <div class="mbox">
      <h3>小贴士</h3>
      <div class="indent">
        <p>标题必须小于255个字符。</p>
        <p>在简介中不能含有任何html标签，系统自动过滤。</p>
      </div>
    </div>
    <div class="mbox">
      <h3>站内导航</h3>
      <div class="indent">
        <p><a href="<%= !@company.blank? ? admin_company_articles_path(@company) : admin_articles_path %>">返回文章列表</a></p>
      </div>
    </div>
  <% end -%>
<% end -%>

app/views/admin/articles/_form.html.erb
<%= javascript_include_tag :ckeditor %>
<%= simple_form_for([:admin, @company, @article], :html => { :multipart => true }) do |f| -%>
  <%= f.error_messages %>
  <div id="post_form_container">
    <div class="main_attributes">
      <div class="inner">
        <%= f.input :title %>
        <%= f.input :summary %>
        <%= f.ckeditor :body, :input_html => { :height => 300, :toolbar=>'Full', :swf_params => { :assetable_type => 'Admin', :assetable_id => current_admin.id } } %>
        <%= f.association :area %>
        <% if !@company.blank? %>
          <%= f.input :company_id, :as => :hidden, :input_html => { :value => @company.id } %>
        <% else -%>
          <%= f.association :company %>
        <% end -%>
        <%= f.input :status, :as => :hidden, :input_html => { :value => Article::STATE[:normal] } %>
        <% if admin_signed_in? %>
          <%= f.input :auther, :as => :hidden, :input_html => { :value => current_admin.login } %>
        <% end -%>
      </div>
    </div>
  </div>
  <div class="other_container">
    <%= f.input :cover, :required => true %>
    <% if @article.cover? %>
      <div class="cover_prview">
        <%= image_tag @article.cover.url %>
      </div>
    <% end -%>
  </div>
  <div class="other_container">
    <%= f.input :pv %>
  </div>
  <div class="actions">
    <%= f.button :submit %>
  </div>
<% end -%>

app/views/admin/articles/edit.html.erb
<% title("修改文章") %>
<%= render "base" %>
<%= render "form" %>

app/views/admin/articles/index.html.erb
<% title("文章列表") %>
<%= render "base" %>
<%= grid(@articles) do |g|
  g.column :column_name => "名称", :attribute_name => "title"
  g.column :column_name => "栏目", :attribute_name => "name", :model_class => "Area" do |article|
    article.area.name
  end
  if @company.blank?
    g.column :column_name => "公司", :attribute_name => "name", :model_class => "Company" do |article|
      article.area.name
    end
  end
  g.column :column_name => "浏览量", :attribute_name => "pv"
  g.column :column_name => "状态", :attribute_name => "status", :auto_reload => true, :custom_filter => Article::STATE do |article|
    t("activerecord.attributes.article.state.#{Article::STATE.key(article.status)}")
  end
  if @company.blank?
    g.column :td_html_attrs => { :class => "actions" } do |article|
      raw "#{link_to("编辑", edit_admin_article_path(article))} | #{link_to("删除", admin_article_path(article), :method => :delete)}"
    end
  else
    g.column :td_html_attrs => { :class => "actions" } do |article|
      raw "#{link_to("编辑", edit_admin_company_article_path(@company, article))} | #{link_to("删除", admin_company_article_path(@company, article), :method => :delete)}"
    end
  end
end -%>

app/views/admin/articles/new.html.erb
<% title("创建文章") %>
<%= render "base" %>
<%= render "form" %>