config/routes.rb
ChinaBeiBao::Application.routes.draw do
  devise_for :admins,
    :controllers => { :sessions => 'admins/sessions', :registrations => "admins/registrations" }
    
  root :to => "home#index"
  
  namespace :admin do
    root :to => 'home#index'
    resources :companies do
      resources :topics
      resources :articles
      resources :routes
    end
    resources :areas, :topics, :articles, :routes, :admins
  end
  
  
  resources :topics, :routes, :articles, :companies, :only => [:index, :show]
  match '/:slug' => 'areas#show', :as => :area
  match '/:slug/topics' => 'topics#index', :as => :area_topics
  match '/:slug/articles' => 'articles#index', :as => :area_articles
  match '/:slug/routes' => 'routes#index', :as => :area_routes  

end

app/models/company.rb
# coding : utf-8
class Company < ActiveRecord::Base
  has_many :topics, :dependent => :destroy
  has_many :articles, :dependent => :destroy
  has_many :routes, :dependent => :destroy
  
  # 验证
  validates_presence_of :name, :tel, :address, :linkman, :summary, :body
  validates_attachment_presence :cover, :message => "不能为空"
  validates_attachment_size :cover, :less_than => 10.megabytes, :message => "必须小于10M"
  validates_attachment_content_type :cover, :content_type => ['image/jpeg', 'image/png', 'image/pjpeg', 'image/gif'],
    :message => "只能是图片"
  
  has_attached_file :cover,  
    :styles => {
      :small => "120x80#",
      :normal => "200x160#",
      :big => "250x168#" 
    },
    :default_style => :normal,
    :url => "#{APP_CONFIG["upload_url"]}/:class/:attachment/:date_path/:id/:style_:hash_name.:extension",
    :path => "#{APP_CONFIG["upload_path"]}/:class/:attachment/:date_path/:id/:style_:hash_name.:extension",
    :default_url => "default/files/:style.jpg",
    :whiny => false
  
end

app/controllers/admin/companies_controller.rb
# coding : utf-8
class Admin::CompaniesController < Admin::ApplicationController
  
  def index
    @companies = initialize_grid(Company)
  end
  
  def new
    @company = Company.new
  end
  
  def create
    @company = Company.new(params[:company])
    if @company.save
      redirect_to admin_companies_path, :notice => "新的公司添加成功！"
    else
      render :new
    end
  end
  
  def edit
    @company = Company.find(params[:id])
  end
  
  def update
    @company = Company.find(params[:id])
    if @company.update_attributes(params[:company])
      redirect_to admin_companies_path, :notice => "公司信息修改成功！"
    else
      render :edit
    end
  end
  
  def destroy
    @company = Company.find(params[:id])
    if @company.destroy
      redirect_to admin_companies_path, :notice => "删除成功！"
    else
      redirect_to admin_companies_path, :alert => "删除失败！"
    end
  end
  
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  
  before_filter :load_areas, :load_sidebar
  
  def show
    @company = Company.find(params[:id])  
  end
  
end

app/helpers/admin/companies_helper.rb
module Admin::CompaniesHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/admin/companies/_base.html.erb
<% content_for :sidebar do -%>
  <% if ["index"].index(action_name) -%>
  <div class="button_to_add_new">
    <div class="button_layout">
      <a href="<%= new_admin_company_path %>"><span>添加新的公司</span></a>
    </div>
  </div>
  <% end -%>
  <% if ["new", "create"].index(action_name) -%>
    <div class="mbox">
      <h3>添加一个新的公司</h3>
      <div class="indent">
        <p>你可以在这里添加一个新的公司，稍后你才可以添加其他内容，比如旅游线路，专题等。</p>
      </div>
    </div>
  <% end -%>
  <% if ["edit", "update"].index(action_name) -%>
    <div class="mbox">
      <h3>修改现有的公司</h3>
      <div class="indent">
        <p>你可以修改现有的公司信息。</p>
      </div>
    </div>
  <% end -%>
  <% if ["edit", "create", "new", "update"].index(action_name) -%>
    <div class="mbox">
      <h3>站内导航</h3>
      <div class="indent">
        <ul class="nav">
          <li><a href="<%= admin_companies_path %>"><span>返回公司列表</span></a></li>
        </ul>
      </div>
    </div>
  <% end -%>
<% end -%>

app/views/admin/companies/_form.html.erb
<%= javascript_include_tag :ckeditor %>
<%= simple_form_for([:admin, @company], :html => { :multipart => true }) do |f| -%>
  <%= f.error_messages %>
  <div id="post_form_container">
    <div class="main_attributes">
      <div class="inner">
        <%= f.input :name %>
        <%= f.input :address %>
        <%= f.input :summary %>
        <%= f.ckeditor :body, :input_html => { :height => 300, :toolbar=>'Full', :swf_params => { :assetable_type => 'Admin', :assetable_id => current_admin.id } } %>
        <%= f.input :tel %>
        <%= f.input :linkman %>
        <%= f.input :qq %>
        <%= f.input :msn %>
      </div>
    </div>
  </div>
  <div id="other_container">
    <%= f.input :cover, :required => true %>
    <% if @company.cover? %>
      <div class="cover_prview">
        <%= image_tag @company.cover.url %>
      </div>
    <% end -%>
  </div>
  <div class="actions">
    <%= f.button :submit %>
  </div>
<% end -%>

app/views/admin/companies/edit.html.erb
<% title "修改公司" %>
<%= render "base" %>
<%= render "form" %>
<% content_for :page_header do -%>
  <h1>修改公司信息</h1>
<% end -%>

app/views/admin/companies/index.html.erb
<% title "公司" %>
<%= render "base" %>
<% content_for :page_header do -%>
  <h1>公司列表</h1>
<% end -%>
<%= grid(@companies) do |g|
  g.column :column_name => "名称", :attribute_name => "name"
  g.column :column_name => "联系人", :attribute_name => "linkman"
  g.column :column_name => "电话", :attribute_name => "tel"
  g.column :column_name => "专题" do |company|
    raw "#{link_to("专题", admin_company_topics_path(company), :title => "查看#{company.name}的专题列表")}"
  end
  g.column :column_name => "文章" do |company|
    raw "#{link_to("文章", admin_company_articles_path(company), :title => "查看#{company.name}的文章列表")}"
  end
  g.column :column_name => "线路" do |company|
    raw "#{link_to("线路", admin_company_routes_path(company), :title => "查看#{company.name}的线路列表")}"
  end
  g.column :td_html_attrs => { :class => "actions" } do |company|
    raw "#{link_to("编辑", edit_admin_company_path(company))} | #{link_to("删除", admin_company_path(company), :method => :delete)}"
  end
end -%>

app/views/admin/companies/new.html.erb
<% title "添加公司" %>
<%= render "base" %>
<%= render "form" %>
<% content_for :page_header do -%>
  <h1>添加一个新的公司</h1>
<% end -%>