config/routes.rb
ChinaBeiBao::Application.routes.draw do
  devise_for :admins,
    :controllers => { :sessions => 'admins/sessions', :registrations => "admins/registrations" }
    
  root :to => "home#index"
  
  namespace :admin do
    root :to => 'home#index'
    resources :companies do
      resources :topics
      resources :articles
      resources :routes
    end
    resources :areas, :topics, :articles, :routes, :admins
  end
  
  
  resources :topics, :routes, :articles, :companies, :only => [:index, :show]
  match '/:slug' => 'areas#show', :as => :area
  match '/:slug/topics' => 'topics#index', :as => :area_topics
  match '/:slug/articles' => 'articles#index', :as => :area_articles
  match '/:slug/routes' => 'routes#index', :as => :area_routes  

end

app/views/shared/_admin_nav.html.erb
<li><a href="<%= admin_root_path %>"<%= raw(" class=\"current\"") if ["home"].index(controller_name) %> title="首页"><%= t("activerecord.models.dashboard") %></a></li>
<li><a href="<%= admin_companies_path %>"<%= raw(" class=\"current\"") if ["companies"].index(controller_name) %> title="旅游公司管理"><%= t("activerecord.models.company") %></a></li>
<li><a href="<%= admin_areas_path %>"<%= raw(" class=\"current\"") if ["areas"].index(controller_name) %> title="栏目管理"><%= t("activerecord.models.area") %></a></li>
<li><a href="<%= admin_topics_path %>"<%= raw(" class=\"current\"") if ["topics"].index(controller_name) %> title="专题管理"><%= t("activerecord.models.topic") %></a></li>
<li><a href="<%= admin_articles_path %>"<%= raw(" class=\"current\"") if ["articles"].index(controller_name) %> title="文章管理"><%= t("activerecord.models.article") %></a></li>
<li><a href="<%= admin_routes_path %>"<%= raw(" class=\"current\"") if ["routes"].index(controller_name) %> title="线路管理"><%= t("activerecord.models.route") %></a></li>
<li><a href="<%= admin_admins_path %>"<%= raw(" class=\"current\"") if ["admins"].index(controller_name) %> title="管理员管理"><%= t("activerecord.models.admin") %></a></li>

app/views/shared/_footer.html.erb
<p class="copyright">Copyright © 2011 <%= Setting.site_name %> <span><%= Setting.version %></span> <%= Setting.icp %> </p>

app/views/shared/_header.html.erb
<div class="logo_and_banner clearfix">
  <h1 class="logo">
    <a href="<%= root_path %>" title="<%= Setting.site_name %>"><%= image_tag "logo.png" %></a>
  </h1>
  <div class="header_banner">
    <%= image_tag "ad/630x90.jpg" %>
  </div>
</div>
<div class="navigation">
  <%= render "shared/navigation" %>
</div>

app/views/shared/_navigation.html.erb
<ul class="clearfix">
  <li <%= raw("class=\"current\"") if ["home"].index(controller_name) %>>
    <a href="<%= root_path %>" title="中国背包网首页">首页</a>
  </li>
  <% @areas.each do |area| -%>
    <li <%= raw "class=\"current\""  if area.slug == params[:slug] %>>
      <a href="<%= area_path(area.slug) %>" title="<%= area.description %>"><%= area.name %></a>
    </li>
  <% end -%>
  <li><a href="http://bbs.chinabeibao.com" title="论坛">论坛</a></li>
  <li><a href="http://home.chinabeibao.com/" title="家园">家园</a></li>
</ul>

app/views/shared/_sidebar.html.erb
<% if !@company.blank? %>
<div class="box">
  <div class="title_wrapper"><h3>俱乐部信息</h3></div>
  <div class="right_company_wrapper clearfix">
    <a href="<%= company_path(@company) %>" title="<%= @company.name %>">
      <%= image_tag @company.cover(:big), :class => "cover", :alt => @company.name %>
    </a>
    <div class="info">
      <ul>
        <li class="name">
          <a href="<%= company_path(@company) %>" title="<%= @company.name %>"><%= @company.name %></a>
        </li>
        <li class="linkman"><span>联系人：</span><%= @company.linkman %></li>
        <li class="address"><span>地址：</span><%= @company.address %></li>
      </ul>
    </div>        
    <p class="summary"><%= truncate @company.summary, :length => 60 %></p>
    <div class="online_icon clearfix">
      <div class="icon"><%= single_qq @company.qq %></div>
      <div class="icon"><%= single_msn @company.msn %></div>
    </div>
  </div>
</div>
<% end -%>
<div class="box <%= "line10" if !@company.blank? %>">
  <div class="title_wrapper"><h3>区域导航</h3></div>
  <div class="right_areas_wrapper">
    <ul class="clearfix">
      <% areas.each do |area| -%>
        <li><a href="<%= area_path(area.slug) %>" title="<%= area.name %>"><%= area.name %></a></li>
      <% end -%>
    </ul>
  </div>
</div>
<div class="box line10">
  <div class="title_wrapper"><h3>最新的旅游线路</h3></div>
  <div class="right_lists_wrapper">
    <ul class="clearfix">
      <% routes.each do |route| -%>
        <li><a href="<%= route_path(route) %>" title="<%= route.title %>"><%= truncate route.title, :length => 17 %></a></li>
      <% end -%>
    </ul>
  </div>
</div>
<div class="box line10">
  <div class="title_wrapper"><h3>最新的旅游专题</h3></div>
  <div class="right_lists_wrapper">
    <ul class="clearfix">
      <% topics.each do |route| -%>
      <li><a href="<%= topic_path(route) %>" title="<%= route.title %>"><%= truncate route.title, :length => 17 %></a></li>
      <% end -%>
    </ul>
  </div>
</div>
<div class="box line10">
  <div class="title_wrapper"><h3>最新的游记攻略</h3></div>
  <div class="right_lists_wrapper">
    <ul class="clearfix">
      <% articles.each do |route| -%>
      <li><a href="<%= article_path(route) %>" title="<%= route.title %>"><%= truncate route.title, :length => 17 %></a></li>
      <% end -%>
    </ul>
  </div>
</div>