config/routes.rb
ChinaBeiBao::Application.routes.draw do
  devise_for :admins,
    :controllers => { :sessions => 'admins/sessions', :registrations => "admins/registrations" }
    
  root :to => "home#index"
  
  namespace :admin do
    root :to => 'home#index'
    resources :companies do
      resources :topics
      resources :articles
      resources :routes
    end
    resources :areas, :topics, :articles, :routes, :admins
  end
  
  
  resources :topics, :routes, :articles, :companies, :only => [:index, :show]
  match '/:slug' => 'areas#show', :as => :area
  match '/:slug/topics' => 'topics#index', :as => :area_topics
  match '/:slug/articles' => 'articles#index', :as => :area_articles
  match '/:slug/routes' => 'routes#index', :as => :area_routes  

end

app/controllers/admin/home_controller.rb
class Admin::HomeController < Admin::ApplicationController
  
  def index
    @companies = Company.order("id desc").limit(5)
    @areas = Area.order("id desc").limit(5)
    @topics = Topic.order("id desc").limit(5)
    @articles = Article.order("id desc").limit(5)
    @routes = Route.order("id desc").limit(5)
  end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  before_filter :load_areas
  
  def index
    @focus_topics = Topic.limit(5)
    @recommend_company = Company.limit(1).order("id desc")
  end
  
end

app/helpers/admin/home_helper.rb
module Admin::HomeHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_index_route.html.erb
<li><a href="<%= route_path(r) %>" title="<%= r.title %>"><%= truncate r.title, :length => 20 %></a><span class="mum"><%= r.pcount %>人</span></li>

app/views/home/_index_topic.html.erb
<div class="info_wrapper">
  <div class="info clearfix">
    <a href="<%= topic_path(t) %>" title="<%= t.title %>">
      <%= image_tag t.cover(:small), :class => "cover", :alt => t.title %>
    </a>
    <h4>
      <a href="<%= topic_path(t) %>" title="<%= t.title %>"><%= truncate t.title, :length => 14 %></a>
    </h4>
  </div>
  <div class="exp_container clearfix">
    <div class="exp">
      <span class="label">推荐指数：</span>
      <span class="star"><%= image_tag "common/star/#{t.rec_num}.png", :alt => "#{t.rec_num}星" %></span>
    </div>
    <div class="exp">
      <span class="label">人气指数：</span>
      <span class="star"><%= image_tag "common/star/#{t.pop_num}.png", :alt => "#{t.pop_num}星" %></span>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<% title "首页" %>
<div class="main_top clearfix">
  <div class="main_topleft">
    <div id="focus" style="visibility:hidden;">
      <% @focus_topics.each do |topic| -%>
        <a href="<%= topic_path(topic) %>"><img src="<%= topic.cover(:normal) %>", alt="<%= topic.title %>" width="600" height="250" /></a>
      <% end -%>
    </div>
  </div>
  <div class="main_topright">
    <div class="box">
      <div class="title_wrapper">
        <h3>推荐俱乐部</h3>
      </div>
      <% @recommend_company.each do |company| -%>
      <div class="basic_info clearfix">
        <a href="<%= company_path(company) %>" title="<%= company.name %>">
          <%= image_tag company.cover(:small), :class => "cover", :alt => company.name %>
        </a>
        <div class="info">
          <ul>
            <li class="name">
              <a href="<%= company_path(company) %>" title="<%= company.name %>"><%= company.name %></a>
            </li>
            <li class="linkman"><span>联系人：</span><%= company.linkman %></li>
            <li class="address"><span>地址：</span><%= company.address %></li>
          </ul>
        </div>
      </div>
      <p class="summary"><%= truncate company.summary, :length => 60 %></p>
      <div class="online_icon clearfix">
        <div class="icon"><%= single_qq company.qq %></div>
        <div class="icon"><%= single_msn company.msn %></div>
      </div>
      <% end -%>
    </div>
  </div>
</div>
<% @areas.each do |area| -%>
<div class="area_container">
  <div class="area_banner"><%= image_tag area.ad(:normal) %></div>
  <div class="area">
    <h2><a href="<%= area_path(area.slug) %>" title="<%= area.name %>"><%= area.name %></a></h2>
    <div class="area_wrapper clearfix">
      <div class="recommend">
        <h3 class="clearfix">
          <span class="title">推荐专题</span>
          <span class="more"><a href="<%= area_topics_path(area.slug) %>" title="查看更多的特色专题">更多</a></span>
        </h3>
        <% area.topics.top.each do |topic| %>
          <%= render "index_topic", :t => topic %>
        <% end -%>
      </div>
      <div class="route">
        <h3 class="clearfix">
          <span class="title">经典线路</span>
          <span class="more"><a href="<%= area_routes_path(area.slug) %>" title="查看更多的经典线路">更多</a></span>
        </h3>
        <ul>
          <% area.routes.top7.each do |route| -%>
            <%= render "index_route", :r => route %>
          <% end -%>
        </ul>
      </div>
      <div class="article">
        <h3 class="clearfix">
          <span class="title">游记攻略</span>
          <span class="more"><a href="<%= area_articles_path(area.slug) %>" title="查看更多的游记攻略">更多</a></span>
        </h3>
        <ul>
          <% area.articles.top2.each_with_index do |article, index| -%>
            <%= render "index_article", :a => article, :i => index %>
          <% end -%>
        </ul>
      </div>
    </div>
  </div>
</div>
<% end -%>
<%= content_for :scripts do -%>
  <%= javascript_include_tag "jquery.KinSlideshow" %>
  <script type="text/javascript">
    $(function() {
      $("#focus").KinSlideshow({
        mouseEvent: "mouseover",
        titleBar: {
          titleBar_height: 30,
          titleBar_bgColor: "#000000",
          titleBar_alpha:0.5
        },
        btn: {
          btn_bgColor: "#FFFFFF",
          btn_bgHoverColor: "#1072aa",
          btn_fontColor: "#000000",
          btn_fontHoverColor: "#FFFFFF",
          btn_borderColor: "#cccccc",
          btn_borderHoverColor: "#1188c0",
          btn_borderWidth: 1
        }
      });
    })
  </script>
<% end -%>